"""empty message

Revision ID: 5a5bed079c6c
Revises: ab3af3e2c0fa
Create Date: 2019-01-15 15:19:35.729713

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a5bed079c6c'
down_revision = 'ab3af3e2c0fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('some_data', sa.String(length=60), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'some_data')
    # ### end Alembic commands ###
