"""empty message

Revision ID: c580feb13d17
Revises: c2738a334c4c
Create Date: 2019-01-26 18:52:28.430385

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c580feb13d17'
down_revision = 'c2738a334c4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'some_data')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('some_data', sa.VARCHAR(length=60), nullable=True))
    # ### end Alembic commands ###
