"""empty message

Revision ID: ed8e18e848cb
Revises: 5a5bed079c6c
Create Date: 2019-01-15 15:21:56.234103

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed8e18e848cb'
down_revision = '5a5bed079c6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'some_data')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('some_data', sa.VARCHAR(length=60), nullable=True))
    # ### end Alembic commands ###
